name: Deploy Backend to Dev Server

on:
  push:
    branches:
      - develop  # fantry-backend 저장소의 develop 브랜치에 push되면 실행

jobs:
  deploy:
    runs-on: self-hosted # 우리 서버의 Runner에서 실행
    
    # API KEY 정의
    env:
      SECRET_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      SECRET_REDIS_PASSWORD: ${{ secrets.PROD_REDIS_PASSWORD }}
      SECRET_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      SECRET_BOOTPAY_ID: ${{secrets.BOOTPAY_ID}}
      SECRET_BOOTPAY_KEY: ${{secrets.BOOTPAY_KEY}}
      SECRET_JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      # 새로운 이메일 키 추가 시 GitHub Secret에 등록 후 아래 처럼 추가하면 됨
      # 아래의 {{ }} 안에서 'secrets.'을 제외한 이름과 깃허브에 등록한 이름과 같아야함.
      # SECRET_EMAIL_API_KEY: ${{ secrets.DEV_EMAIL_API_KEY }}
    
    # 실제 수행할 단계(들)
    steps:
      - name: Execute backend deployment script
        run: ~/scripts/deploy-backend-prod.sh
