name: Deploy Backend to Dev Server

on:
  push:
    branches:
      - develop  # fantry-backend 저장소의 develop 브랜치에 push되면 실행

jobs:
  deploy:
    runs-on: self-hosted # 우리 서버의 Runner에서 실행

    # 실제 수행할 단계(들)
    steps:
      - name: Execute backend deployment script
        run: ~/scripts/deploy-backend-dev.sh